### ISSUE TITLE
[FEATURE REQUEST] Add issue templates

### ISSUE THREAD

**Issue by darigovresearch** [jyjblrd/Mocap-Drones#15]
Having templates would allow for consistency across common types of issues and pull requests along with automatically tagging them as appropriate

The default ones can help with getting enough context and scale up contributions

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests

- [ ] Bug issue template
- [ ] Feature request template

**Comment by darigovresearch** [comment]
Pull request https://github.com/jyjblrd/Mocap-Drones/pull/16 would resolve this issue

**Comment by jyjblrd** [comment]
thanks 👍
