### ISSUE TITLE
About IR markers powering

### ISSUE THREAD

**Issue by clennpillo** [jyjblrd/Mocap-Drones#52]
hi, jyjblrd

I have a question about IR markers powering.

My IR marker 's rated voltage is 1.5V，I got three IR markers attached to my drone.

And I have 3.7V battery on the drone， how should I power the IR markers ?

I have now connected three infrared lights in series and powered the series circuit with the 3.7V battery. The lights do turn on, but I am not sure if this is the correct approach. Can you show me your approach ?

**Comment by jyjblrd** [comment]
I used a led calculator to determine what resistor to use. eg: https://ledcalculator.net/
