### ISSUE TITLE
How to write embedded code.

### ISSUE THREAD

**Issue by cultist123** [jyjblrd/Mocap-Drones#55]
I want to know how you write code for Arduino and how you choose and implement communication protocols. I want to implement similar functionality on another embedded board but don't know where to start.

**Comment by jyjblrd** [comment]
I would recommend using the arduino IDE if you are a beginner, there are a lot of libraries and it supports arduino, esp8266, and esp32 boards.

There are plenty of tutorials on how to program in the arduino IDE.
